<a href="https://colab.research.google.com/github/Zukui/CHE358/blob/master/02b_multiple_linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Least square estimation using matrix inverse formula

In [0]:
import numpy as np
from scipy import linalg
np.random.seed(seed=42) # make the example reproducible

# Dataset
N, P = 50, 4
X = np.random.normal(size= N * P).reshape((N, P))

## Our model needs an intercept so we add a column of 1s:
X[:, 0] = 1
print(X[:5, :])
theta = np.array([10, 1., .5, 0.1]) # true model parameters
e = np.random.normal(size=N)
y = np.dot(X, theta) + e

# Estimate the parameters
Xpinv = linalg.pinv2(X)   # (X'X)^-1*X'
thetahat = np.dot(Xpinv, y)
print("Estimated theta:\n", thetahat)

[[ 1.         -0.1382643   0.64768854  1.52302986]
 [ 1.         -0.23413696  1.57921282  0.76743473]
 [ 1.          0.54256004 -0.46341769 -0.46572975]
 [ 1.         -1.91328024 -1.72491783 -0.56228753]
 [ 1.          0.31424733 -0.90802408 -1.4123037 ]]
Estimated theta:
 [10.14742501  0.57938106  0.51654653  0.17862194]
